name: random-workflow
on:
  push
env: 
  MARKET "COSTCO"
  NUMBER: 7
jobs:
  hello-jobs:
      runs-on: ubuntu-latest
      steps:
       - name: Download the code
         uses: actions/checkout@v5
      - name: lets check if we downloaded the code or not
        run: ls
